/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PCover: typeof import('./src/components/PCover.vue')['default']
    PPaperboard: typeof import('./src/components/PPaperboard.vue')['default']
  }
}
